[versions]
kotlinxCoroutines = "1.10.2"
androidxAppcompat = "1.7.1"
androidxCoreKtx = "1.16.0"
androidxLifecycleRuntimeKtx = "2.9.0"
androidxActivityCompose = "1.12.3"
googleMaterial = "1.13.0"
androidxComposeBom = "2026.01.01"
androidxNavigationCompose = "2.9.4"
capsule = "2.1.0"

[libraries]
kotlinxCoroutinesCore = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinxCoroutines" }
kotlinxCoroutinesAndroid = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "kotlinxCoroutines" }

androidxAppcompat = { module = "androidx.appcompat:appcompat", version.ref = "androidxAppcompat" }
androidxCoreKtx = { module = "androidx.core:core-ktx", version.ref = "androidxCoreKtx" }
androidxLifecycleRuntimeKtx = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "androidxLifecycleRuntimeKtx" }
androidxActivityCompose = { module = "androidx.activity:activity-compose", version.ref = "androidxActivityCompose" }

googleMaterial = { module = "com.google.android.material:material", version.ref = "googleMaterial" }

androidxComposeBom = { module = "androidx.compose:compose-bom", version.ref = "androidxComposeBom" }
androidxComposeUi = { module = "androidx.compose.ui:ui" }
androidxComposeUiToolingPreview = { module = "androidx.compose.ui:ui-tooling-preview" }
androidxComposeMaterial3 = { module = "androidx.compose.material3:material3" }
androidxComposeMaterialIconsExtended = { module = "androidx.compose.material:material-icons-extended" }
androidxComposeRuntimeLivedata = { module = "androidx.compose.runtime:runtime-livedata" }
androidxNavigationCompose = { module = "androidx.navigation:navigation-compose", version.ref = "androidxNavigationCompose" }
androidxComposeUiTooling = { module = "androidx.compose.ui:ui-tooling" }

capsule = { module = "com.github.Kyant0:Capsule", version.ref = "capsule" }

[bundles]
coroutines = ["kotlinxCoroutinesCore", "kotlinxCoroutinesAndroid"]
androidxBase = ["androidxAppcompat", "androidxCoreKtx", "androidxLifecycleRuntimeKtx", "androidxActivityCompose"]
composeUi = ["androidxComposeUi", "androidxComposeUiToolingPreview", "androidxComposeMaterial3", "androidxComposeMaterialIconsExtended", "androidxComposeRuntimeLivedata", "androidxNavigationCompose"]
