[versions]
androidxAnnotation = "1.9.1"
androidxCoreKtx = "1.17.0"

[libraries]
androidxAnnotation = { module = "androidx.annotation:annotation", version.ref = "androidxAnnotation" }
androidxCoreKtx = { module = "androidx.core:core-ktx", version.ref = "androidxCoreKtx" }
